---
abstract: 'Precision classes for Modern Perl'
author:
  - 'Ali Anari <ali@anari.me>'
build_requires:
  File::Spec: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Module::Loaded: '0'
  Test::Modern: '0'
  Test::More: '0'
  perl: '5.006'
  strict: '0'
  warnings: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.030, CPAN::Meta::Converter version 2.143240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: MooseX-Modern
requires:
  Moose: '0'
  Moose::Exporter: '0'
  Moose::Util::TypeConstraints: '0'
  MooseX::AttributeShortcuts: '0'
  MooseX::HasDefaults::RO: '0'
  namespace::autoclean: '0'
resources:
  bugtracker: https://github.com/aanari/MooseX-Modern/issues
  repository: git://github.com/aanari/MooseX-Modern.git
version: '0.0101'
